10 PRINT "Characteristics of Generation Z:"
20 PRINT "- Technological Fluency"
30 PRINT "  Example: Proficient in using smartphones, social media, and digital tools."
40 PRINT "- Diversity"
50 PRINT "  Example: Values cultural and ethnic diversity."
60 PRINT "- Inclusion"
70 PRINT "  Example: Supports equal opportunities for all individuals."
80 PRINT "- Mental Health Awareness"
90 PRINT "  Example: Emphasizes the importance of mental health and self-care."
100 PRINT "- Social Activism"
110 PRINT "  Example: Actively participates in movements for social justice and environmental sustainability."
120 PRINT "- Individuality"
130 PRINT "  Example: Prefers unique and personalized choices in career and lifestyle."
140 PRINT "- Flexibility"
150 PRINT "  Example: Adapts well to remote work and non-traditional career paths."
160 END
